ARG OTP_VERSION

FROM docker.io/library/erlang:${OTP_VERSION}
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

ARG THRIFT_VERSION
ARG BUILDARCH

RUN apt-get --yes update && \
    apt-get --yes --no-install-recommends install iproute2=5.10.0-4 sshpass=1.09-1+b1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q -O- "https://github.com/valitydev/thrift/releases/download/${THRIFT_VERSION}/thrift-${THRIFT_VERSION}-linux-${BUILDARCH}.tar.gz" \
    | tar -xvz -C /usr/local/bin/

ENV NETUNREACH_NETWORK="10.254.254.0/24"
ENV NETUNREACH_ADDRESS="10.254.254.10"

COPY ./test_resources/ssh/ /root/.ssh/
RUN chown -R root:root /root/.ssh && \
    chmod 600 /root/.ssh/*

COPY ./test_resources/entrypoint.sh.dev /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

ENV CHARSET=UTF-8
ENV LANG=C.UTF-8
ENV SERVICE_NAME=mg
CMD ["/bin/bash"]

EXPOSE 4369
EXPOSE 8022
