service_name: mg

#dist_node_name: mg@${POD_IP}
#dist_port:
#    mode: static
#    port: 31337

erlang:
    ipv6: false
    secret_cookie_file: /opt/mg/etc/cookie

opentelemetry:
    # TODO Describe sampling
    # Name of the service to use in recording machinegun's spans
    service_name: machinegun
    # For now spans processed always in batches.
    # We support only "otlp" traces exporter
    exporter:
        # Supports only "http/protobuf" or "grpc"
        protocol: http/protobuf
        endpoint: http://jaeger:4318

logging:
    out_type: stdout
    level: warning
    formatter:
        level_map:
            'emergency': 'ERROR'
            'alert': 'ERROR'
            'critical': 'ERROR'
            'error': 'ERROR'
            'warning': 'WARN'
            'notice': 'INFO'
            'info': 'INFO'
            'debug': 'DEBUG'

woody_server:
    ip: "::"
    port: 8022
    max_concurrent_connections: 8000
    http_keep_alive_timeout: 3000ms
    shutdown_timeout: 5s

storage:
    type: riak
    host: riakdb
    port: 8087
    pool:
        size: 100
        queue_max: 500
    batch_concurrency_limit: 10
    connect_timeout: 500ms
    request_timeout: 10s
    index_query_timeout: 60s

worker:
    message_queue_len_limit: 1000

process_registry:
    module: mg_core_procreg_gproc

cluster:
    discovery:
        type: dns
        options:
            domain_name: machinegun-ha-headless
            sname: mg
    scaling: partition_based
    partitioning:
        capacity: 5
        max_hash: 4095
    reconnect_timeout: 5000

namespaces:
    NS:
        timers:
            scan_interval: 60s
            scan_limit: 2000
            capacity: 3500
            min_scan_delay: 5s
        overseer:
            scan_interval: 60m
            min_scan_delay: 5s
        retries:
            storage:
                type: exponential
                max_retries: infinity
                factor: 2
                timeout: 10ms
                max_timeout: 60s
            timers:
                type: exponential
                max_retries: 100
                factor: 2
                timeout: 2s
                max_timeout: 30m
            processor:
                type: exponential
                max_retries:
                    max_total_timeout: 1d
                factor: 2
                timeout: 10ms
                max_timeout: 60s
            continuation:
                type: exponential
                max_retries: infinity
                factor: 2
                timeout: 10ms
                max_timeout: 60s
        event_sinks:
            kafka:
                type: kafka
                topic: test_transaction
                client: default_kafka_client
        processor:
            url: http://mg-0:8023/processor
            pool_size: 2000
            http_keep_alive_timeout: 3000ms
        unload_timeout: 180s
        shutdown_timeout: 5s

kafka:
    default_kafka_client:
        endpoints:
            - host: "kafka1"
              port: 9092
            - host: "kafka2"
              port: 9092
            - host: "kafka3"
              port: 9092
        producer:
            compression: no_compression
            partition_onwire_limit: 1
            ack_timeout: 10s
            required_acks: all_isr
            partition_buffer_limit: 256
            max_linger: 0ms
            max_linger_count: 0
            max_batch_size: 1M
            max_retries: 3
            retry_backoff: 500ms
